GET http://Chowde-Publi-mIhb1Tu9w3FW-408573748.us-east-1.elb.amazonaws.com/api/restaurants/nearby?lat=6.6018&lng=3.3515
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvamUzNDNAdGVzdC5jb20iLCJyb2xlIjoiQ3VzdG9tIiwiaWF0IjoxNzY5OTc2MjU2LCJleHAiOjE3NzAwMTIyNTZ9.yC6rk0Amw7EygT8mVvPr9PX3CWe4pgH0ElPvV6PIoO4